# Generated by Django 3.1.3 on 2021-01-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_auto_20210116_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
