# Generated by Django 3.1.3 on 2021-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='비밀 여부'),
        ),
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='비밀 여부'),
        ),
    ]
