# Generated by Django 3.1.3 on 2021-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210116_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='secret',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='비밀 여부'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='비밀 여부'),
        ),
    ]
