# Generated by Django 3.1.3 on 2021-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210116_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='verify_comment',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='댓글 허용'),
        ),
    ]
